Feat:- Input and text-utilities component
anurag-kkumarr/burgeonX-ui pull request #5
Opened 2022-02-19 11:41 UTC by anurag-kkumarr

Added Input component
   -textbox
   -with validation and errors style
  
Text-utilities added
    -headings
    -small text
    -gray text
   -center text

2022-02-19 11:52 UTC, harshitpaliwal95 requested changes
- use rems as unit otherwise if will be tough to add responsiveness

2022-02-19 11:52 UTC, harshitpaliwal95 commented on components/CSS/card.css
> +    width: 500px;
use rem as units

2022-02-20 09:14 UTC, Balakumar3018 approved these changes
Looks good to me

2022-02-20 09:15 UTC, masraniJay approved these changes
Looks good.

2022-02-20 09:21 UTC, merged